services:
  - type: web
    name: bfhl-backend
    runtime: node
    plan: free
    rootDir: backend
    buildCommand: npm install
    startCommand: npm start

  - type: web
    name: bfhl-frontend
    runtime: static
    rootDir: frontend
    buildCommand: ""
    staticPublishPath: .
